[package]
name = "seed_rs_realworld"
version = "0.1.0"
authors = ["Martin Kavík <martin@kavik.cz>"]
edition = "2018"


[lib]
crate-type = ["cdylib"]


[dependencies]
#seed = "^0.3.7"
seed = { git = "https://github.com/David-OConnor/seed" }
wasm-bindgen = "^0.2.45"
tool = "0.2.1"
